# This is a github workflow file

name: learning-github-actions
run-name: ${{ github.actor }} is learning github actions 

# specify the event to be triggered
on: [ push ]
jobs: 
  check-bats-version: 
    name: check-bats-version
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v3 
      - uses: actions/setup-node@v3
        with: 
          node-version: '14'
          
      - run : npm install -g bats
      - run : bats -v
